name: test

on:
  push:
    branches:
      - test

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12']
        include:
          - python-version: '3.12'
            tag: 'cp312-manylinux_x86_64'
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 twine
        pip install -r requirements.txt
        pip install cibuildwheel
    # - name: Lint with flake8 for syntax errors
    #   run: |
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Build manylinux Python wheels using cibuildwheel
      run: cibuildwheel --platform linux --output-dir dist
      env:
        CIBW_BEFORE_ALL: 'dnf install -y epel-release; dnf config-manager --set-enabled crb; dnf install --nogpgcheck https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-$(rpm -E %rhel).noarch.rpm -y; dnf install --nogpgcheck https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-$(rpm -E %rhel).noarch.rpm -y; dnf update -y; dnf install -y libjpeg-turbo-devel ffmpeg ffmpeg-libs ffmpeg-devel libffi-devel'
        CIBW_MANYLINUX_X86_64_IMAGE: 'manylinux_2_28'
        CIBW_BUILD: ${{ matrix.tag }}
    - name: Install wheel
      run: pip install vi3o --no-index -f dist/
    - name: Install test dependencies
      run: |
        sudo apt-get --yes install ffmpeg
        pip install pytest py
    - name: Test wheel
      run: |
        cp -r test ~
        cd ~/test
        HEADLESS=1 py.test
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/*
